language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="cowabloga:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="cowabloga" OCAML_VERSION="4.07"
  - PACKAGE="cowabloga" OCAML_VERSION="4.08"
  - PACKAGE="cowabloga" OCAML_VERSION="4.09"
